[
  {
    "_id": 1,
    "name": "Michael Jordan",
    "img_name": "images/Michael.jpeg",
    "brand": "Fleer",
    "year": 1986,
    "card_number": "#57",
    "meta": "1986 Fleer #57",
    "sport": "Basketball",
    "grade": "PSA 10",
    "price": 250000,
    "currency": "USD"
  },
  {
    "_id": 2,
    "name": "Wayne Gretzky",
    "img_name": "images/Wayne.jpeg",
    "brand": "O-Pee-Chee",
    "year": 1979,
    "card_number": "#18",
    "meta": "1979 O-Pee-Chee #18",
    "sport": "Hockey",
    "grade": "PSA 10",
    "price": 150000,
    "currency": "USD"
  },
  {
    "_id": 3,
    "name": "Tom Brady",
    "img_name": "images/Tom.jpeg",
    "brand": "Playoff Contenders",
    "year": 2000,
    "card_number": "#144",
    "meta": "2000 Playoff Contenders #144",
    "sport": "Football",
    "grade": "PSA 8",
    "price": 125000,
    "currency": "USD"
  },
  {
    "_id": 4,
    "name": "Kobe Bryant",
    "img_name": "images/Kobe.jpeg",
    "brand": "Topps Chrome",
    "year": 1996,
    "card_number": "#138",
    "meta": "1996 Topps Chrome #138",
    "sport": "Basketball",
    "grade": "PSA 10",
    "price": 95000,
    "currency": "USD"
  },
  {
    "_id": 5,
    "name": "Lionel Messi",
    "img_name": "images/Messi.jpeg",
    "brand": "Topps",
    "year": 2011,
    "card_number": "",
    "meta": "2011 Topps",
    "sport": "Soccer",
    "grade": "PSA 10",
    "price": 85000,
    "currency": "USD"
  },
  {
    "_id": 6,
    "name": "Derek Jeter",
    "img_name": "images/derek.jpeg",
    "brand": "SP",
    "year": 1993,
    "card_number": "#279",
    "meta": "1993 SP #279",
    "sport": "Baseball",
    "grade": "PSA 10",
    "price": 75000,
    "currency": "USD"
  },
  {
    "_id": 7,
    "name": "LeBron James",
    "img_name": "images/LeBron.jpeg",
    "brand": "Upper Deck",
    "year": 2003,
    "card_number": "#23",
    "meta": "2003 Upper Deck #23",
    "sport": "Basketball",
    "grade": "PSA 9",
    "price": 65000,
    "currency": "USD"
  },
  {
    "_id": 8,
    "name": "Aaron Judge",
    "img_name": "images/Judge.jpeg",
    "brand": "Topps",
    "year": 2013,
    "card_number": "#AAR13",
    "meta": "2013 Topps Prospect #AAR13",
    "sport": "Baseball",
    "grade": "PSA 9",
    "price": 45000,
    "currency": "USD"
  }
]
